INCLUDE IRVINE32.INC
	.DATA
	MSG1 BYTE"THIS IS STRING:",0
	MSG2 BYTE "AMIR SAEED",0
	MSG3 BYTE "REVERSE STRING IS :",0
	.CODE
	MAIN PROC
	
	MOV EDX,OFFSET MSG1
	CALL WRITESTRING
	CALL CRLF
	MOV EDX,OFFSET MSG2
	CALL WRITESTRING

	CALL CRLF
	MOV EDX,OFFSET MSG3
	CALL WRITESTRING
	
	
	MOV ECX,LENGTHOF MSG2
	MOV ESI ,OFFSET MSG2                 
NASIR:
	MOV AL,[ESI]                                    ; A,m,i,r, ,s,a,e,e,d
	PUSH EAX
	INC ESI
LOOP NASIR
	MOV ECX,11
FROMSTACK:
	POP EAX
	CALL WRITECHAR                 
	INC ESI
LOOP FROMSTACK
	CALL CRLF
EXIT
MAIN ENDP
END MAIN
	
	
	
	